version: '3'
services:
  frontend:
    build: app/
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: .
    expose:
      - "5000"
    command: gunicorn -b :5000 --access-logfile - --error-logfile - api:app && flask db migrate
    volumes:
      - db_data:/data

volumes:
  db_data:
